---
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Shrikeh\HelloWorld\:
    resource: '../src/'
    
  hello_world.console.command_factory.celestial_greeting:
    class: Shrikeh\SymfonyApp\Console\Action\Cqrs\CommandFactory\Decorator\CorrelatedCommand
    decorates: Shrikeh\HelloWorld\Console\Greet\CelestialGreetingFactory
    arguments:
      $inner: '@.inner'
  
  Shrikeh\HelloWorld\Console\Greet:
    arguments:
      $commandFactory: '@hello_world.console.command_factory.celestial_greeting'
      $resultFormatter: '@Shrikeh\HelloWorld\Console\Greet\BodyGreetedFormatter'
    configurator: '@hello_world.console.greet.configurator'
    
  hello_world.console.greet.configurator:
    class: Shrikeh\SymfonyApp\Console\Action\Configurator\InputConfigurator
    constructor: 'fromServiceTagIterator'
    arguments:
      - !tagged_iterator { tag: hello_world.console.greet.input }
    
  Shrikeh\HelloWorld\Console\Input\Greeting:
    arguments:
      $description: 'The greeting to give the celestial body'
    tags:
      - { name: hello_world.console.greet.input, priority: 10 }
  Shrikeh\HelloWorld\Console\Input\CelestialBody:
    arguments:
      $description: 'The celestial body to be greeted'
    tags:
      - { name: hello_world.console.greet.input, priority: 5 }

  hello_world.http.query_factory.greetings:
    class: Shrikeh\SymfonyApp\Http\Action\Cqrs\QueryFactory\Decorator\CorrelatedQuery
    decorates: Shrikeh\HelloWorld\Http\Greetings\GreetingsFactory
    arguments:
      $inner: '@.inner'

  Shrikeh\HelloWorld\Http\Greetings:
    arguments:
      $queryFactory: '@hello_world.http.query_factory.greetings'
      $resultResponseFactory: '@Shrikeh\HelloWorld\Http\Greetings\CelestialGreetingsResponseFactory'
  
  Ergebnis\Json\Normalizer\Normalizer: '@Ergebnis\Json\Normalizer\ChainNormalizer'
  
  Ergebnis\Json\Normalizer\ChainNormalizer:
    arguments:
      - '@Ergebnis\Json\Normalizer\IndentNormalizer'
        
  Ergebnis\Json\Normalizer\IndentNormalizer: ~
  
  Ergebnis\Json\Printer\Printer: ~
  Ergebnis\Json\Printer\PrinterInterface: '@Ergebnis\Json\Printer\Printer'
  
  Ergebnis\Json\Normalizer\Format\Indent:
    constructor: 'fromSizeAndStyle'
    arguments:
      $size: 2
      $style: 'space'
  
  _instanceof:
    Shrikeh\SymfonyApp\Http\Action:
      tags:
        - { name: 'controller.service_arguments' }
    Shrikeh\App\Query\QueryHandler:
      tags:
        - { name: 'messenger.message_handler', bus: 'query.bus' }
    Shrikeh\App\Command\CommandHandler:
      tags:
        - { name: 'messenger.message_handler', bus: 'command.bus' }
          
    
  Symfony\Component\Serializer\Encoder\JsonEncoder: ~
  Symfony\Component\Serializer\Normalizer\ObjectNormalizer: ~
  Symfony\Component\Serializer\Serializer:
    arguments:
      $normalizers:
        - '@Symfony\Component\Serializer\Normalizer\ObjectNormalizer'
      $encoders:
        - '@Symfony\Component\Serializer\Encoder\JsonEncoder'

  Symfony\Bridge\PsrHttpMessage\HttpFoundationFactoryInterface: '@Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory'
  Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface: '@Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory'
  Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory: ~
  Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory: ~
  Symfony\Bridge\PsrHttpMessage\ArgumentValueResolver\PsrServerRequestResolver: ~
  Symfony\Bridge\PsrHttpMessage\EventListener\PsrResponseListener: ~
